# Default configuration file for Forge AntiXray mod by DrexHD

# Default values
enabled = true

# World specific values
[overworld]
enabled = true
engineMode = 3
maxBlockHeight = 256
updateRadius = 5
lavaObscures = true
hiddenBlocks = ["#forge:ores", "raw_copper_block", "raw_iron_block", "raw_gold_block", "chest", "trapped_chest", "barrel", "ender_chest"]
replacementBlocks = ["stone", "deepslate", "andesite", "calcite", "diorite", "dirt", "granite", "gravel", "sand", "tuff", "mossy_cobblestone", "obsidian", "clay", "infested_stone", "amethyst_block", "budding_amethyst"]

[the_nether]
enabled = true
engineMode = 5
maxBlockHeight = 128
updateRadius = 3
lavaObscures = true
hiddenBlocks = ["ancient_debris", "nether_quartz_ore", "nether_gold_ore", "gold_block", "gilded_blackstone"]